using NodeAssets.Compilers;
using NodeAssets.Core.Commands;
using NUnit.Framework;
using System.IO;

namespace NodeAssets.Test.Core.Compilers
{
    [TestFixture]
    public class CoffeeCompilerTest
    {
        private CoffeeCompiler _compiler;

        [SetUp]
        public void Init()
        {
            _compiler = new CoffeeCompiler(new NodeExecutor(TestContext.CurrentContext.TestDirectory + "/../../Node", TestContext.CurrentContext.TestDirectory + "/../../Node/node.exe"));
        }

        [Test]
        public void Compile_InvalidCoffeeFile_Exception()
        {
            Assert.ThrowsAsync(typeof(CompileException), async () =>
            {
                var coffee = File.ReadAllText(TestContext.CurrentContext.TestDirectory + "/../../Data/invalidCoffee.coffee");
                var output = await _compiler.Compile(coffee, null).ConfigureAwait(false);
            });
        }

        [Test]
        public void Compile_ValidCoffeeFile_Compiles()
        {
            var coffee = File.ReadAllText(TestContext.CurrentContext.TestDirectory + "/../../Data/exampleCoffee.coffee");

            var output = _compiler.Compile(coffee, null).Result.Output;

            Assert.AreEqual("// Generated by CoffeeScript 1.10.0\n(function() {\n  var helloWorld;\n\n  helloWorld = function() {\n    return console.log('Hello World!');\n  };\n\n  helloWorld();\n\n}).call(this);\n", output);
        }
    }
}
